analytics_dashboard/courses/urls.py
# pylint: disable=no-value-for-parameter
from django.conf import settings
from django.conf.urls import url, include

from courses import views
from courses.views import enrollment, engagement, performance, csv, learners

CONTENT_ID_PATTERN = r'(?P<content_id>(?:i4x://?[^/]+/[^/]+/[^/]+/[^@]+(?:@[^/]+)?)|(?:[^/]+))'
PROBLEM_PART_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'problem_part_id')
ASSIGNMENT_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'assignment_id')
PROBLEM_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'problem_id')
SECTION_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'section_id')
SUBSECTION_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'subsection_id')
VIDEO_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'video_id')
PIPELINE_VIDEO_ID = r'(?P<pipeline_video_id>([^/+]+[/+][^/+]+[/+][^/]+)+[|]((?:i4x://?[^/]+/[^/]+/[^/]+' \
                    r'/[^@]+(?:@[^/]+)?)|(?:[^/]+)+))'
TAG_VALUE_ID_PATTERN = r'(?P<tag_value>[\w-]+)'

answer_distribution_regex = \
    r'^graded_content/assignments/{assignment_id}/problems/{problem_id}/parts/{part_id}/answer_distribution/$'.format(
        assignment_id=ASSIGNMENT_ID_PATTERN, problem_id=PROBLEM_ID_PATTERN, part_id=PROBLEM_PART_ID_PATTERN)

ungraded_answer_distribution_regex = \
    r'^ungraded_content/sections/{}/subsections/{}/problems/{}/parts/{}/answer_distribution/$'.format(
        SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN, PROBLEM_ID_PATTERN, PROBLEM_PART_ID_PATTERN)

video_timeline_regex = \
    r'^videos/sections/{}/subsections/{}/modules/{}/timeline/$'.format(
        SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN, VIDEO_ID_PATTERN)

ENROLLMENT_URLS = ([
    url(r'^activity/$', enrollment.EnrollmentActivityView.as_view(), name='activity'),
    url(r'^geography/$', enrollment.EnrollmentGeographyView.as_view(), name='geography'),
    url(r'^demographics/age/$', enrollment.EnrollmentDemographicsAgeView.as_view(), name='demographics_age'),
    url(r'^demographics/education/$', enrollment.EnrollmentDemographicsEducationView.as_view(),
        name='demographics_education'),
    url(r'^demographics/gender/$', enrollment.EnrollmentDemographicsGenderView.as_view(), name='demographics_gender'),
], 'enrollment')

ENGAGEMENT_URLS = ([
    url(r'^content/$', engagement.EngagementContentView.as_view(), name='content'),
    url(r'^videos/$', engagement.EngagementVideoCourse.as_view(), name='videos'),
    # ordering of the URLS is important for routing the the section, subsection, etc. correctly
    url(video_timeline_regex, engagement.EngagementVideoTimeline.as_view(), name='video_timeline'),
    url(r'^videos/sections/{}/subsections/{}/$'.format(SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN),
        engagement.EngagementVideoSubsection.as_view(),
        name='video_subsection'),
    url(r'^videos/sections/{}/$'.format(SECTION_ID_PATTERN),
        engagement.EngagementVideoSection.as_view(),
        name='video_section'),
], 'engagement')

PERFORMANCE_URLS = ([
    url(r'^ungraded_content/$', performance.PerformanceUngradedContent.as_view(), name='ungraded_content'),
    url(ungraded_answer_distribution_regex, performance.PerformanceUngradedAnswerDistribution.as_view(),
        name='ungraded_answer_distribution'),
    url(r'^ungraded_content/sections/{}/subsections/{}/$'.format(SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN),
        performance.PerformanceUngradedSubsection.as_view(),
        name='ungraded_subsection'),
    url(r'^ungraded_content/sections/{}/$'.format(SECTION_ID_PATTERN),
        performance.PerformanceUngradedSection.as_view(),
        name='ungraded_section'),
    url(r'^graded_content/$', performance.PerformanceGradedContent.as_view(), name='graded_content'),
    url(r'^graded_content/(?P<assignment_type>[\w-]+)/$',
        performance.PerformanceGradedContentByType.as_view(),
        name='graded_content_by_type'),
    url(answer_distribution_regex, performance.PerformanceAnswerDistributionView.as_view(), name='answer_distribution'),

    # This MUST come AFTER the answer distribution pattern; otherwise, the answer distribution pattern
    # will be interpreted as an assignment pattern.
    url(r'^graded_content/assignments/{}/$'.format(ASSIGNMENT_ID_PATTERN),
        performance.PerformanceAssignment.as_view(),
        name='assignment'),
    url(r'^learning_outcomes/$',
        performance.PerformanceLearningOutcomesContent.as_view(),
        name='learning_outcomes'),
    url(r'^learning_outcomes/{}/$'.format(TAG_VALUE_ID_PATTERN),
        performance.PerformanceLearningOutcomesSection.as_view(),
        name='learning_outcomes_section'),
    url(r'^learning_outcomes/{}/problems/{}/$'.format(TAG_VALUE_ID_PATTERN, PROBLEM_ID_PATTERN),
        performance.PerformanceLearningOutcomesAnswersDistribution.as_view(),
        name='learning_outcomes_answers_distribution'),
    url(r'^learning_outcomes/{}/problems/{}/{}/$'.format(TAG_VALUE_ID_PATTERN, PROBLEM_ID_PATTERN,
                                                         PROBLEM_PART_ID_PATTERN),
        performance.PerformanceLearningOutcomesAnswersDistribution.as_view(),
        name='learning_outcomes_answers_distribution_with_part'),
], 'performance')

CSV_URLS = ([
    url(r'^enrollment/$', csv.CourseEnrollmentCSV.as_view(), name='enrollment'),
    url(r'^enrollment/geography/$', csv.CourseEnrollmentByCountryCSV.as_view(), name='enrollment_geography'),
    url(r'^enrollment/demographics/age/$',
        csv.CourseEnrollmentDemographicsAgeCSV.as_view(),
        name='enrollment_demographics_age'),
    url(r'^enrollment/demographics/education/$',
        csv.CourseEnrollmentDemographicsEducationCSV.as_view(),
        name='enrollment_demographics_education'),
    url(r'^enrollment/demographics/gender/$',
        csv.CourseEnrollmentDemographicsGenderCSV.as_view(),
        name='enrollment_demographics_gender'),
    url(r'^engagement/activity_trend/$',
        csv.CourseEngagementActivityTrendCSV.as_view(),
        name='engagement_activity_trend'),
    url(r'^engagement/videos/{}/$'.format(PIPELINE_VIDEO_ID),
        csv.CourseEngagementVideoTimelineCSV.as_view(),
        name='engagement_video_timeline'),
    url(r'^performance/graded_content/problems/{}/answer_distribution/{}/$'.format(CONTENT_ID_PATTERN,
                                                                                   PROBLEM_PART_ID_PATTERN),
        csv.PerformanceAnswerDistributionCSV.as_view(),
        name='performance_answer_distribution'),
    url(r'problem_responses/', csv.PerformanceProblemResponseCSV.as_view(), name='performance_problem_responses')
], 'csv')

LEARNER_URLS = ([
    url(r'^$', learners.LearnersView.as_view(), name='learners'),
], 'learners')

COURSE_URLS = [
    # Course homepage. This should be the entry point for other applications linking to the course.
    url(r'^$', views.CourseHome.as_view(), name='home'),
    url(r'^enrollment/', include(ENROLLMENT_URLS)),
    url(r'^engagement/', include(ENGAGEMENT_URLS)),
    url(r'^performance/', include(PERFORMANCE_URLS)),
    url(r'^csv/', include(CSV_URLS)),
    url(r'^learners/', include(LEARNER_URLS)),
]

app_name = 'courses'
urlpatterns = [
    url('^$', views.CourseIndex.as_view(), name='index'),
    url(r'^{}/'.format(settings.COURSE_ID_PATTERN), include(COURSE_URLS))
]

analytics_dashboard/learner_analytics_api/urls.py
from django.conf.urls import url, include

app_name = 'learner_analytics_api'
urlpatterns = [
    url(r'^v0/', include('learner_analytics_api.v0.urls'))
]

analytics_dashboard/learner_analytics_api/v0/urls.py
from django.conf import settings
from django.conf.urls import url

from . import views


USERNAME_PATTERN = r'(?P<username>.+)'

app_name = 'v0'
urlpatterns = [
    url(r'^learners/{}/$'.format(USERNAME_PATTERN), views.LearnerDetailView.as_view(), name='LearnerDetail'),
    url(r'^learners/$', views.LearnerListView.as_view(), name='LearnerList'),
    url(r'^learners.csv$', views.LearnerListCSV.as_view(), name='LearnerListCSV'),
    url(r'^engagement_timelines/{}/$'.format(USERNAME_PATTERN),
        views.EngagementTimelinesView.as_view(),
        name='EngagementTimeline'),
    url(r'^course_learner_metadata/{}/$'.format(settings.COURSE_ID_PATTERN),
        views.CourseLearnerMetadataView.as_view(),
        name='CourseMetadata'),
]

analytics_dashboard/urls.py
# pylint: disable=line-too-long,no-value-for-parameter
import os

from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views import defaults
from django.views.generic import RedirectView
from django.views.i18n import javascript_catalog

# pylint suggests importing analytics_dashboard.core, which causes errors in our AMI
# pylint: disable=relative-import
from core import views


admin.autodiscover()

js_info_dict = {
    'packages': ('core', 'courses',),
}

urlpatterns = [
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^status/$', views.status, name='status'),
    url(r'^health/$', views.health, name='health'),
    url(r'^courses/', include('courses.urls')),
    url(r'^admin/', admin.site.urls),
    # TODO: the namespace arg is deprecated, but python-social-auth urls.py doesn't specify app_name so we are stuck
    # using namespace. Once python-social-auth is updated to fix that, remove the namespace arg.
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/login/$',
        RedirectView.as_view(url=reverse_lazy('social:begin', args=['edx-oidc']), permanent=False, query_string=True),
        name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^accounts/logout_then_login/$', views.logout_then_login, name='logout_then_login'),
    url(r'^test/auto_auth/$', views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^announcements/', include('pinax.announcements.urls', namespace='pinax_announcements')),
]

urlpatterns += [
    url(r'^api/learner_analytics/', include('learner_analytics_api.urls'))
]


def debug_page_not_found(request):
    return defaults.page_not_found(request, AttributeError('foobar'))


def debug_permission_denied(request):
    return defaults.permission_denied(request, AttributeError('foobar'))


if settings.DEBUG:  # pragma: no cover
    urlpatterns += [
        url(r'^403/$', debug_permission_denied),
        url(r'^404/$', debug_page_not_found),
        url(r'^500/$', defaults.server_error),
        url(r'^503/$', views.ServiceUnavailableView.as_view()),
    ]

    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=import-error, wrong-import-position, wrong-import-order

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

analytics_dashboard/core/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """ Custom user model. """

    # TODO: it may not be necessary to store the language
    # preferences. Saving it in the session should be enough.
    language = models.CharField(max_length=255, null=True, choices=settings.LANGUAGES, default=None)

    @property
    def access_token(self):
        try:
            return self.social_auth.first().extra_data[u'access_token']  # pylint: disable=no-member
        except Exception:  # pylint: disable=broad-except
            return None

    class Meta(object):
        get_latest_by = 'date_joined'
        db_table = 'analytics_dashboard_user'   # Legacy table name

analytics_dashboard/django_rjs/models.py
# This app does not require any models.

analytics_dashboard/core/views.py
import json
import logging
import uuid

import django
from django.conf import settings
from django.contrib.auth import get_user_model, login, authenticate, REDIRECT_FIELD_NAME
from django.db import connection, DatabaseError
from django.http import HttpResponse, Http404
from django.shortcuts import redirect
from django.views.generic import View, TemplateView
from django.core.urlresolvers import reverse_lazy
from analyticsclient.client import Client
from analyticsclient.exceptions import TimeoutError

from analytics_dashboard.courses import permissions


logger = logging.getLogger(__name__)
User = get_user_model()

# Health constants
OK = u'OK'
UNAVAILABLE = u'UNAVAILABLE'


def status(_request):
    return HttpResponse()


def health(_request):
    overall_status = analytics_api_status = database_status = UNAVAILABLE

    try:
        cursor = connection.cursor()
        cursor.execute("SELECT 1")
        cursor.fetchone()
        cursor.close()
        database_status = OK
    except DatabaseError as e:
        logger.exception('Insights database is not reachable: %s', e)
        database_status = UNAVAILABLE

    try:
        client = Client(base_url=settings.DATA_API_URL, auth_token=settings.DATA_API_AUTH_TOKEN, timeout=0.35)
        # Note: client.status.healthy sends a request to the health endpoint on
        # the Analytics API.  The request may throw a TimeoutError.  Currently,
        # other exceptions are caught by the client.status.healthy method
        # itself, which will return False in those cases.
        analytics_api_healthy = client.status.healthy
    except TimeoutError as e:
        logger.exception('Analytics API health check timed out from dashboard: %s', e)
        analytics_api_status = UNAVAILABLE
    else:
        if analytics_api_healthy:
            analytics_api_status = OK
        else:
            logger.error('Analytics API health check failed from dashboard')
            analytics_api_status = UNAVAILABLE

    overall_status = OK if (analytics_api_status == database_status == OK) else UNAVAILABLE

    data = {
        'overall_status': overall_status,
        'detailed_status': {
            'database_connection': database_status,
            'analytics_api': analytics_api_status
        }
    }

    return HttpResponse(json.dumps(data), content_type='application/json', status=200 if overall_status == OK else 503)


class AutoAuth(View):
    """
    Creates and authenticates a new User.

    If the setting ENABLE_AUTO_AUTH is not set to True, returns a 404.
    """

    def get(self, request, *_args, **_kwargs):
        if not settings.ENABLE_AUTO_AUTH:
            raise Http404

        if not settings.AUTO_AUTH_USERNAME_PREFIX:
            raise ValueError('AUTO_AUTH_USERNAME_PREFIX must be set!')

        # Create a new user
        username = password = settings.AUTO_AUTH_USERNAME_PREFIX + uuid.uuid4().hex[0:20]
        user = User.objects.create_user(username, password=password)

        # Grant user access to demo course
        permissions.set_user_course_permissions(user, ['edX/DemoX/Demo_Course'])

        # Login the new user
        user = authenticate(username=username, password=password)
        login(request, user)

        return redirect('/')


def logout(request, next_page='/', template_name=None,
           redirect_field_name=REDIRECT_FIELD_NAME, extra_context=None):
    """
    Revoke user permissions and logout
    """

    # Revoke permissions
    permissions.revoke_user_course_permissions(request.user)

    # Back to the standard logout flow
    return django.contrib.auth.views.logout(request, next_page, template_name, redirect_field_name,
                                            extra_context)


def logout_then_login(request, login_url=reverse_lazy('login'), extra_context=None):
    """
    Logout then login
    """
    permissions.revoke_user_course_permissions(request.user)
    return django.contrib.auth.views.logout_then_login(request, login_url, extra_context)


class ServiceUnavailableView(TemplateView):
    """
    Service unavailable error page requesting users to wait and reload the page.
    """
    template_name = "503.html"


class LandingView(TemplateView):
    """
    Displays a public landing page when users first come to the site.
    """
    template_name = "core/landing.html"

    def dispatch(self, request, *args, **kwargs):
        """ Non logged in users will be directed to the landing page. """
        if request.user.is_anonymous():
            return super(LandingView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('courses:index')

    def get_context_data(self, **kwargs):
        context = super(LandingView, self).get_context_data(**kwargs)
        context['research_url'] = settings.RESEARCH_URL
        context['open_source_url'] = settings.OPEN_SOURCE_URL
        context['show_research'] = settings.SHOW_LANDING_RESEARCH and settings.RESEARCH_URL
        audience_message_column_width = 6
        if context['show_research']:
            audience_message_column_width = 4
        context['audience_message_column_width'] = audience_message_column_width

        return context

analytics_dashboard/help/views.py
from help import HELP_CONTEXT_TOKEN_NAME


class ContextSensitiveHelpMixin(object):
    """
    Adds page-specific data to enable context-sensitive help.
    """

    help_token = None

    def get_context_data(self, **kwargs):
        context = super(ContextSensitiveHelpMixin, self).get_context_data(**kwargs)
        context[HELP_CONTEXT_TOKEN_NAME] = self.help_token
        return context

analytics_dashboard/templates/_announcement.html
{% load i18n %}

<div class="announcement-container"
     data-dismiss-url="{{ dismiss_url }}"
     data-view="announcement">
    <div class="grid-container grid-manual">
        <div class="row">
            <div class="col col-1 md-col-1">
                <div class="icon"><span class="fa fa-bullhorn" aria-hidden="true"></span></div>
            </div>

            <div class="col col-11 sm-col-11 md-col-10">
                {% if message %}
                    {{ message|safe }}
                {% else %}
                    <div class="message">
                        <h1>{{ title }}</h1>
                        <p>{{ body|safe }}</p>
                    </div>
                {% endif %}
            </div>

            {% if dismiss_url %}
                <div class="col col-1 md-col-1">
                    {% csrf_token %}
                    <a class="dismiss">
                        <span class="fa fa-times" aria-hidden="true"></span>
                        <span class="sr-only">{% trans "Close" %}</span>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

analytics_dashboard/templates/announcements.html
{% load soapbox %}
{% load pinax_announcements_tags %}

{% get_messages_for_page view.page_name as soapbox_messages %}
{% for message in soapbox_messages %}
  {% include "_announcement.html" with message=message %}
{% endfor %}

{% announcements as announcements_list %}
{% with announcements_list|first as announcement %}
  {% if announcement %}
    {% include "_announcement.html" with body=announcement.content title=announcement.title dismiss_url=announcement.dismiss_url %}
  {% endif %}
{% endwith %}

analytics_dashboard/templates/base-error.html
{% extends "base_dashboard.html" %}

{% load i18n %}
{% load dashboard_extras %}

{% block view-name %}view-system{% endblock view-name %}

{# These are intentionally left blank. #}
{% block header %}{% endblock %}
{% block lens_navigation %}{% endblock %}
{% block announcements %}{% endblock %}
{% block footer %}{% endblock %}

{% block content-outer %}
  <div class="site-wrapper">

    <div class="site-wrapper-inner">

      <div class="cover-container">

        <div class="masthead clearfix">
          <div class="inner">
            {% include 'brand.html' with class_prefix='masthead' %}
          </div>
        </div>

        <div class="inner cover">
          <h1 class="cover-heading">
            <span class="error-code">{% block error-code %}{% endblock %}</span>
            <span class="error-title">{% block error-title %}{% endblock %}</span>
          </h1>

          <p class="lead error-copy">
              {% block error-copy %}
              If you continue to see this error, use the link below to contact our support team.
              {% endblock error-copy %}
          </p>

          <p class="lead">
            {% block buttons %}
              <a href="mailto:{% settings_value 'SUPPORT_EMAIL' %}" class="btn btn-lg btn-primary" data-role="support-email"
                 title="{% trans 'Use our support tool to ask questions or share feedback.' %}">
                <span class="ico fa fa-life-ring" aria-hidden="true"></span>
                {% captureas platform_name %}{% settings_value "PLATFORM_NAME" %}{% endcaptureas %}

                {# Translators: This intention here is that a user clicks a button to contact a support group (e.g. edX Support, or MITx Support). Reorder the placeholder as you see fit. #}
                {% blocktrans %}Contact {{ platform_name }} Support{% endblocktrans %}
              </a>
            {% endblock %}
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

analytics_dashboard/templates/brand.html
{% load staticfiles %}
{% load i18n %}
{% load dashboard_extras %}

{% captureas insights_url %}/{% endcaptureas %}
<a class="{{ class_prefix }}-brand" href="{{ insights_url }}" data-track-type="click"
    data-track-event="edx.bi.ui.menu.navigated" data-track-url="{{ insights_url }}" data-track-target-scope="insights"
    data-track-target-lens="home" data-track-menu-depth="home" data-track-link-name="logo">
  <div class="{{ class_prefix }}-brand-logo" alt="{% settings_value 'PLATFORM_NAME' %}"></div>
  <span class="{{ class_prefix }}-brand-app">{% settings_value 'APPLICATION_NAME' %}</span>
</a>

analytics_dashboard/templates/header.html
{% load i18n %}
{% load firstof from future %}
{% load dashboard_extras %}

{% comment %}
Partial: App-wide header element
{% endcomment %}

{% include "_skip_link.html" with content_id="content" %}
<header class="navbar navbar-default" id="nav">
  <div class="grid-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
        <span class="sr-only">{% trans 'Toggle navigation' %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      {% include 'brand.html' with class_prefix='navbar' %}
      {% if course_id %}
      <ul class="nav navbar-nav">
        <li>
            {% captureas course_home_url %}{% url 'courses:home' course_id=course_id %}{% endcaptureas %}
            <a href="{{ course_home_url }}" class="navbar-link active-course-name"
                data-track-type="click" data-track-event="edx.bi.ui.menu.navigated"
                data-track-text="{% firstof course_name course_id %}"
                data-track-url="{{ course_home_url }}" data-track-target-scope="course"
                data-track-target-lens="home" data-track-menu-depth="home" data-track-link-name="course_title">
                {% firstof course_name course_id %}</a>
        </li>
      </ul>
      {% endif %}
    </div>

    <div class="collapse navbar-collapse" id="main-nav">
      <ul class="nav navbar-nav navbar-right">
        {% if help_url %}
          <li>
            <a id="help" class="navbar-link " data-track-type="click" data-track-event="edx.bi.help.clicked"
               href="{{ help_url }}" target="_blank">{% trans "Help" %}</a>
          </li>
        {% endif %}
        <li class="dropdown">
          <button class="dropdown-toggle active-user navbar-link" data-toggle="dropdown"
             aria-controls="userDropdownMenu" id="userMenu">
            <span class="sr-only">{% trans "Menu for" %}</span>
            <span class="ico-user fa fa-graduation-cap" aria-hidden="true"></span>
            <span class="active-user-name">{{ request.user.username }}</span>
            <span class="ico ico-indicator fa fa-caret-down" aria-hidden="true"></span>
          </button>

          <ul id="userDropdownMenu" class="dropdown-menu active-user-nav" tabindex="-1"
              aria-labelledby="userMenu">
            <li>
              {% captureas logout_url %}{% url 'logout' %}{% endcaptureas %}
              <a class="active-user-nav-logout" href="{{ logout_url }}" data-track-type="click"
                  data-track-event="edx.bi.ui.menu.navigated" data-track-text="Logout"
                  data-track-url="{{ logout_url }}" data-track-target-scope="insights"
                  data-track-target-lens="logout" data-track-menu-depth="home" data-track-link-name="logout">
                  {% trans "Logout" %}</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- / navbar-collapse -->
  </div>
  <!-- / container -->
</header>
<!-- / navbar -->

analytics_dashboard/templates/lens-navigation.html
{% load i18n %}
{% load dashboard_extras %}
{% comment %}
Partial for displaying the lens navigation and the sections within the lenses.
{% endcomment %}

{% if primary_nav_items %}
  {#  Translators: Application here refers to the web site/application being used (e.g. the dashboard). #}
  <nav class="navbar navbar-default lens-nav" role="navigation" aria-label="{% trans "Application" %}">
    <div class="grid-container">
      <ul class="nav navbar-nav">
        <li>
          {% captureas course_home_url %}{% url 'courses:home' course_id=course_id %}{% endcaptureas %}
          <a href="{{ course_home_url }}" class="course-label link-label"
              data-track-type="click" data-track-event="edx.bi.ui.menu.navigated"
              data-track-text="Course Home" data-track-url="{{ course_home_url }}"
              data-track-target-scope="course" data-track-target-lens="home" data-track-menu-depth="home"
              data-track-link-name="course_home">
            {#  Translators: This refers to the homepage of a course. #}
            {% trans "Course Home" %}
          </a>
        </li>
        <li class="dropdown">
          <button class="dropdown-toggle navbar-link" data-toggle="dropdown" id="lensPrimaryMenu"
              aria-controls="lensDropdownMenu">
            <span class="link-label">
              <span class="sr-only">{% trans "Navigation Menu." %}</span>
              <span class="ico fa {{ primary_nav_item.icon }}" aria-hidden="true"></span>
              {{ primary_nav_item.translated_text }}
              {# Translators: This refers to the active tab/navigation item. #}
              <span class="sr-only">({% trans "Active" %})</span>
              <span class="ico ico-indicator fa fa-caret-down" aria-hidden="true"></span>
            </span>
          </button>

          <ul id="lensDropdownMenu" class="dropdown-menu" aria-labelledby="lensPrimaryMenu" tabindex="-1">
            {% for item in primary_nav_items %}
              <li>
                {% captureas lens_url %}{{ item.href }}{{ item.fragment }}{% endcaptureas %}
                <a href="{{ lens_url }}" data-track-type="click"
                    data-track-event="edx.bi.ui.menu.navigated"
                    data-track-text="{{ item.text }}" data-track-url="{{ lens_url }}"
                    data-track-target-scope="{{ item.scope }}" data-track-target-lens="{{ item.lens }}"
                    data-track-target-report="{{ item.report }}" data-track-target-depth="{{ item.depth }}"
                    data-track-menu-depth="lens" data-track-link-name="{{ item.lens }}">
                  <span class="link-label">
                    <span class="ico fa {{ item.icon }}" aria-hidden="true"></span> {{ item.translated_text }}
                  </span>
                </a>
              </li>
            {% endfor %}
          </ul>
        </li>

        {% include "submenu_navigation.html" with nav_items=secondary_nav_items lens=primary_nav_item.lens depth="report" %}
      </ul>
    </div>
  </nav>
{% endif %}